### PR TITLE
[WIP] Use only noexcept for C++>=11

### PR DESCRIPTION
**Pull request by ymontmarin**
With some modern compiler with light install, `_GLIBCXX_USE_NOEXCEPT` is deprecated and only `noexcept` should be use. This PR make it more consistence and is still compatible with c++ < 11

### CODE REVIEW

**Comment by nim65s** [comment]
We enforce C++ >= 14 here too :)

**Comment by ymontmarin** [comment]
Ok ! should I modify my PR to only let lines like:
```
  virtual ~path_planning_failed() noexcept {};
  virtual const char* what() const noexcept { return msg_.c_str(); };
```

**Comment by nim65s** [comment]
Yes,

**Comment by ymontmarin** [comment]
@nim65s Is the new implementation ok ?
thanks !
Yann

**Pull request merged**
