### PR TITLE
Make ConstraintSet child classes serializable.

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by jmirabel** [comment]
For reference, when I use commit 6a1abf4 on top of this PR, serialization stops working. It seems boost::serialization is not able to identify the correct class for a reason I do not understand.

**Comment by florent-lamiraux** [comment]
Isn't it due to the intermediate class CarLike ?

**Comment by jmirabel** [comment]
What makes you think so ?
It *shouldn't* as it is not the same class hierarchy.

**Comment by jmirabel** [comment]
By the way, why do we have two class ReedsSheppPath and DubinsPath ? Shouldn't there only be different steering methods (and may be different constructor or static function in ReedsSheppPath) ?

**Comment by jmirabel** [comment]
I understood the issue and will provide a fix.

**Pull request merged**
